"""Clear subtitles operator for VSE_Transcribe.

Removes all subtitle Text Strips created by the addon.
"""

from __future__ import annotations

try:
    import bpy
    from bpy.types import Operator, Context
    _HAS_BPY = True
except ImportError:
    class Operator:
        pass
    class Context:
        pass
    _HAS_BPY = False


class VSETRANSCRIBE_OT_clear_subtitles(Operator):
    """Clear all generated subtitle Text Strips."""

    bl_idname = "vse_transcribe.clear_subtitles"
    bl_label = "Clear Subtitles"
    bl_description = "Remove all subtitle Text Strips generated by VSE_Transcribe"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context: Context) -> bool:
        """Check if operator can run."""
        if not _HAS_BPY:
            return False
        settings = context.scene.vse_transcribe
        # Can run if there are generated strips or if sequence editor exists
        return bool(settings.generated_strips or context.scene.sequence_editor)

    def execute(self, context: Context) -> set:
        """Clear subtitle strips."""
        if not _HAS_BPY:
            self.report({"ERROR"}, "Not running inside Blender")
            return {"CANCELLED"}

        settings = context.scene.vse_transcribe
        scene = context.scene

        if not scene.sequence_editor:
            self.report({"INFO"}, "No sequence editor, nothing to clear")
            return {"FINISHED"}

        sequencer = scene.sequence_editor

        # Clear via StripManager
        from VSE_Transcrib.core.strip_manager import StripManager

        try:
            manager = StripManager(scene, sequencer)
            count = manager.clear_managed_strips()

            # Clear stored strip names
            settings.generated_strips.clear()

            if count > 0:
                self.report({"INFO"}, f"Removed {count} subtitle strips")
            else:
                self.report({"INFO"}, "No managed subtitle strips found")

            return {"FINISHED"}

        except Exception as e:
            self.report({"ERROR"}, f"Failed to clear subtitles: {e}")
            return {"CANCELLED"}


# Registration handled by __init__.py